(ns lang-site.db.mock-data
  (:require
   [cljs.spec :as s]
   [lang-site.components.templates :as t]))

(def card [:widget/card :cart/title :card/question :card/answer])
(def grid [:widget/grid :grid/data :grid/content])
(def header [:widget/header :header/title :header/content])
(def header-drawer [:widget/header-drawer :header-drawer/title :header-drawer/content])
(def link [:widget/link :link/text :link/icon :link/href])
(def login-card [:widget/login-card])
(def menu-item [:widget/menu-item :menu-item/text])
(def page [:widget/page :page/content])
(def register-card [:widget/register-card :register-card/user
                    :register-card/email :register-card/password])
(def sentence [:widget/sentence :sentence/text :sentence/group :sentence/language])
(def user [:widget/user :user/name :user/email :user/password])
(def user-card [:widget/user-card :user-card/user :user-card/data])

(def many  {:db/cardinality :db.cardinality/many})
(def ref   {:db/valueType :db.type/ref})
(def com   {:db/isComponent true})
(def index {:db/index true})

(def schema
  {:header/content        (merge many ref com)
   :header-drawer/content (merge many ref com)
   :card/question         (merge      ref com)
   :card/answer           (merge      ref com)
   :card/content          (merge many ref com)
   :cloze-card/question   (merge      ref com)
   :close-card/answer     (merge      ref com)
   :grid/content          (merge many ref com)
   :page/content          (merge many ref com)
   :user-card/user        (merge      ref com)
   :register-card/temp    (merge      ref com)
   :widget/type           {:db/index true}})

(defn make [template & data]
  ((apply t/make template) data))

(def fixtures
  [((apply t/make sentence) -1 "First Sentence\n" 100 :sentence.language/eng)
   ((apply t/make sentence) -2 "Second Sentence\n" 100 :sentence.language/tur)
   ((apply t/make header) -4 "Language test site" [-15 -16 -17])
   ((apply t/make menu-item) -15 "About")
   ((apply t/make menu-item) -16 "Contact")
   ((apply t/make menu-item) -17 "Legal Information")
   ((apply t/make link) -23 "User" "user" "#user")
   ((apply t/make link) -5  "Home" "home" "#")
   ((apply t/make link) -6  "Inbox" "inbox" "#inbox")
   ((apply t/make link) -7  "Delete" "delete" "#delete")
   ((apply t/make link) -18 "Report" "report" "#report")
   ((apply t/make link) -19 "Forum" "forum" "#forum")
   ((apply t/make link) -20 "Flag" "flag" "#flag")
   ((apply t/make link) -21 "Promos" "local_offer" "#local_offer")
   ((apply t/make link) -22 "Bob" "bob@email.com" "password")
   (t/user-card-t -24 -22 -22)
   ((apply t/make login-card) -23)
   #_(t/cloze-card-template -25 "Cloze" -1 -2)
   ((apply t/make header-drawer) -8 "Language test site" [-5 -6 -7 -18 -19 -20])
   ((apply t/make grid) -9 "Placeholder" [-12 -14 -24])
 #_(t/grid-template -25 "Users grid" [-24])
   ((apply t/make page) -10 [-4 -8 -9])
   (t/card-t -12 "Card 1" -1 -2)
   (t/card-t -13 "Card 2" -1 -2)
   ((apply t/make register-card) -14 "" "" "")])
